version: '3.1'
name: irriga-mais
services:
  server:
    build: ./
    restart: always
    volumes:
      - ./irriga_mais:/app
    command: ["python3", "/app/manage.py", "runserver", "0.0.0.0:8080"]
    ports:
      - '8080:8080'

  prometheus:
    image: prom/prometheus:v2.14.0
    volumes:
     - ./prometheus/:/etc/prometheus/
    # command:
    #   - 'config.file=/etc/prometheus/prometheus.yml'
    ports:
      - 9090:9090
  grafana:
    image: grafana/grafana:latest
    ports:
      - 3000:3000