global:
  scrape_interval: 15s
  evaluation_interval: 15s
rule_files:
  # - "first.rules"
  # - "second.rules"

scrape_configs:
  - job_name: irriga-mais
    static_configs:
      - targets: ["server:8080"]
