# Generated by Django 4.2.7 on 2023-12-05 03:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Fazenda',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('email', models.CharField(max_length=255)),
                ('senha', models.CharField(max_length=255)),
                ('localizacao_latitude', models.FloatField()),
                ('localizacao_longitude', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='TokenAuth',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=255)),
                ('data_expiracao', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='PivoIrrigacao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('token', models.CharField(max_length=255)),
                ('descricao', models.CharField(max_length=255)),
                ('tipo', models.CharField(max_length=50)),
                ('estado', models.BooleanField(default=True)),
                ('fazenda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='irrigacao.fazenda')),
            ],
        ),
        migrations.CreateModel(
            name='EventoIrrigacao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_hora_inicio', models.DateTimeField(auto_now_add=True)),
                ('duracao', models.DurationField()),
                ('status', models.CharField(choices=[('concluido', 'Concluído'), ('em_andamento', 'Em Andamento'), ('agendado', 'Agendado'), ('erro', 'Erro durante o processo')], default='agendado', max_length=20)),
                ('fazenda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='irrigacao.fazenda')),
                ('pivo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='irrigacao.pivoirrigacao')),
            ],
        ),
    ]
